services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/docs || exit 1" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s
